version: "3.8"
services:

  # Database
  project-postgres:
    image:  "postgres:14.12"
    container_name: "project-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

