version: "3.8"
services:

  # Orders
  order-service:
    depends_on:
      - helios-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 8002:8002
    environment:
      #   Buildpacks environment variable to enable debug through a socket on port 8002
      # - BPL_DEBUG_ENABLED=true
      # - BPL_DEBUG_PORT=8002
      # - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      # - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://helios-postgres:5432/order_heliosdb
      - SPRING_FLYWAY_URL=jdbc:postgresql://helios-postgres:5432/order_heliosdb


  # Database
  helios-postgres:
    image:  "postgres:14.12"
    container_name: "helios-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

